import type { TelemetryEventName } from './types';

export const TELEMETRY_EVENT_NAMES = [
  'onboarding_started',
  'training_choice_shown',
  'training_choice_selected',
  'onboarding_step_completed',
  'onboarding_skipped',
  'onboarding_completed',
  'onboarding_failed',
  'coach_bubble_shown',
  'coach_bubble_dismissed',
  'lobby_created',
  'lobby_copied',
  'lobby_shared',
  'lobby_joined',
  'lobby_ready',
  'lobby_expired',
  'lobby_cancelled',
  'lobby_poll_failed',
  'lobby_entered_match',
  'daily_viewed',
  'daily_started',
  'daily_resumed',
  'daily_completed',
  'streak_updated',
  'weekly_rank_viewed',
  'daily_error',
  'match_completed',
  'rank_viewed',
  'move_conflict',
  'sync_failed',
  'phaser_booted',
  'phaser_destroyed',
  'phaser_runtime_error',
  'api_error',
  'pwa_recovery',
  'blitz_started',
  'blitz_move_submitted',
  'blitz_deadline_warning',
  'blitz_timeout_requested',
  'blitz_timeout_resolved',
  'blitz_completed',
  'blitz_rematch_clicked',
  'blitz_abandoned',
  'recap_viewed',
  'recap_replay_started',
  'recap_shared',
  'rematch_started',
  'board_unlock_viewed',
  'board_unlock_purchased',
  'board_unlock_failed',
  'board_size_selected'
] as const satisfies readonly TelemetryEventName[];

export const TELEMETRY_PROPERTY_KEYS = [
  'mode',
  'screen',
  'step',
  'status',
  'phase',
  'date',
  'dailyId',
  'scoreBucket',
  'rankBucket',
  'attempts',
  'streakCurrent',
  'streakBest',
  'durationBucket',
  'retryable',
  'errorCode',
  'result',
  'version',
  'source',
  'choice',
  'boardSize',
  'costXp',
  'spendableBucket',
  'turnLimitMs',
  'deadlineVersion',
  'timeoutCount',
  'moveCount',
  'outcomeReason'
] as const;

export function isTelemetryEventName(value: string): value is TelemetryEventName {
  return TELEMETRY_EVENT_NAMES.includes(value as TelemetryEventName);
}

export function isAllowedTelemetryProperty(value: string): boolean {
  return TELEMETRY_PROPERTY_KEYS.includes(value as (typeof TELEMETRY_PROPERTY_KEYS)[number]);
}
