import type { TelemetryEventName } from './types';

export const TELEMETRY_EVENT_NAMES = [
  'onboarding_started',
  'training_choice_shown',
  'training_choice_selected',
  'onboarding_step_completed',
  'onboarding_skipped',
  'onboarding_completed',
  'onboarding_failed',
  'coach_bubble_shown',
  'coach_bubble_dismissed',
  'player_signed_out',
  'lobby_created',
  'lobby_copied',
  'lobby_shared',
  'lobby_joined',
  'lobby_ready',
  'lobby_expired',
  'lobby_cancelled',
  'lobby_poll_failed',
  'lobby_entered_match',
  'daily_viewed',
  'daily_started',
  'daily_resumed',
  'daily_completed',
  'streak_updated',
  'weekly_rank_viewed',
  'daily_error',
  'match_completed',
  'rank_viewed',
  'move_conflict',
  'sync_failed',
  'phaser_booted',
  'phaser_destroyed',
  'phaser_runtime_error',
  'api_error',
  'pwa_recovery',
  'blitz_started',
  'blitz_move_submitted',
  'blitz_deadline_warning',
  'blitz_timeout_requested',
  'blitz_timeout_resolved',
  'blitz_completed',
  'blitz_rematch_clicked',
  'blitz_abandoned',
  'recap_viewed',
  'recap_replay_started',
  'recap_shared',
  'rematch_started',
  'board_unlock_viewed',
  'board_unlock_purchased',
  'board_unlock_failed',
  'board_size_selected',
  'ios_runtime_detected',
  'ios_offline_state_changed',
  'ios_offline_retry',
  'ios_offline_recovered',
  'ios_wrapper_error',
  'season_viewed',
  'season_task_progressed',
  'season_reward_unlocked',
  'season_reward_claimed',
  'season_completed',
  'season_expired',
  'season_progress_error',
  'rules_help_opened',
  'rules_help_topic_viewed',
  'rules_contextual_hint_shown',
  'rules_tutorial_replay_started',
  'rules_help_closed',
  'rules_help_error',
  'bot_profile_viewed',
  'bot_profile_selected',
  'bot_move_chosen',
  'bot_decision_timeout',
  'bot_match_completed',
  'bot_fallback_used'
] as const satisfies readonly TelemetryEventName[];

export const TELEMETRY_PROPERTY_KEYS = [
  'mode',
  'screen',
  'step',
  'status',
  'phase',
  'date',
  'dailyId',
  'scoreBucket',
  'rankBucket',
  'attempts',
  'streakCurrent',
  'streakBest',
  'durationBucket',
  'retryable',
  'errorCode',
  'result',
  'version',
  'source',
  'choice',
  'boardSize',
  'costXp',
  'spendableBucket',
  'turnLimitMs',
  'deadlineVersion',
  'timeoutCount',
  'moveCount',
  'outcomeReason',
  'runtimeMode',
  'appVersion',
  'buildNumber',
  'networkState',
  'serviceWorker',
  'seasonId',
  'rewardId',
  'topic',
  'profileId',
  'difficulty',
  'newlyClaimed',
  'xp'
] as const;

export function isTelemetryEventName(value: string): value is TelemetryEventName {
  return TELEMETRY_EVENT_NAMES.includes(value as TelemetryEventName);
}

export function isAllowedTelemetryProperty(value: string): boolean {
  return TELEMETRY_PROPERTY_KEYS.includes(value as (typeof TELEMETRY_PROPERTY_KEYS)[number]);
}
